// Phase 13 Task 13.3: Inventory watchdog — a pluggable step for the autonomous
// agent loop. Forecasts the product watchlist, auto-drafts POs for critical
// items and fires notifications when configured.
import { bulkForecast, ForecastOptions, InventoryForecast } from "./predictive-engine.js";
import { createPoDraft, PurchaseOrder } from "./po-store.js";
import { handleEcommerceSendNotification } from "../tools/notify.js";

export interface WatchdogProduct {
    platform?: string;
    productId: string;
    currentStock: number;
    salesHistory: Array<{ date: string; unitsSold: number }>;
}

export interface WatchdogConfig {
    products: WatchdogProduct[];
    options?: ForecastOptions;
    autoCreatePo?: boolean;       // default true
    notifyOnCritical?: boolean;   // default false
    poNote?: string;
}

export interface WatchdogResult {
    ranAt: string;
    checkedProducts: number;
    critical: InventoryForecast[];
    warnings: number;
    purchaseOrder: PurchaseOrder | null;
    notifications: Array<{ status: string; channel: string; detail: string }>;
}

export async function runInventoryWatchdog(config: WatchdogConfig): Promise<WatchdogResult> {
    const ranAt = new Date().toISOString();
    const forecasts = bulkForecast(config.products, config.options);
    const critical = forecasts.filter(f => f.risk === "critical");
    const warnings = forecasts.filter(f => f.risk === "warning").length;

    let purchaseOrder: PurchaseOrder | null = null;
    const notifications: Array<{ status: string; channel: string; detail: string }> = [];

    if (critical.length > 0) {
        if (config.autoCreatePo !== false) {
            purchaseOrder = await createPoDraft({
                items: critical.map(f => ({
                    platform: f.platform,
                    productId: f.productId,
                    qty: f.suggestedReorderQty,
                })),
                note: config.poNote || `Auto-generated by inventory watchdog (lead time ${critical[0]?.leadTimeDays ?? "n/a"} days)`,
            });
        }

        if (config.notifyOnCritical) {
            const message = `🚨 [Inventory Watchdog] สินค้าวิกฤต ${critical.length} รายการ:\n` +
                critical.map(f => `- ${f.productId}: เหลือ ${f.currentStock} ชิ้น (~${f.daysOfCover} วัน) แนะนำสั่ง ${f.suggestedReorderQty}`).join("\n");
            const res = await handleEcommerceSendNotification({ action: "send", channel: "telegram", message });
            const parsed = JSON.parse((res as any).content[0].text);
            notifications.push(parsed.notification);
        }
    }

    return {
        ranAt,
        checkedProducts: forecasts.length,
        critical,
        warnings,
        purchaseOrder,
        notifications,
    };
}
